### ISSUE TITLE
SD card image

### ISSUE THREAD

**Issue by appjaws** [jdevelop/passkeeper#2]
Hi Eugene,
I am a 72 year old new to programming.
Your project has got me fired up. Its such a great idea I have all the parts and printed a modified case.
I am completely lost as to how to create an image and put it onto a SD card.
Does the application need to be built in Linux?
Is there a free version of Docker?
Better still would it be possible for you to construct and send me an image that I could put on a 4GB card.
Hope to hear from you soon
keep up the good work
kind regards
Paul

**Comment by jdevelop** [comment]
https://passkeeper-dist.s3.amazonaws.com/sdcard.img.gz should work, just gunzip it and use `dd if=sdcard.img of=/dev/sda bs=1M`

https://www.techwalla.com/articles/how-to-disable-write-protection-on-a-hard-drive for Windows could be helpful.

**Comment by appjaws** [comment]
Thank you so much for the file.
I have loaded the image file using dd from cygwin package.
132+1 records in
132+1 records out
138412544 bytes (138 MB, 132 MiB) copied, 0.3237 s, 428 MB/s
The red light is on on the rfid card but no lights on the raspberrypi zero
http://10.101.1.1 no response.
Its almost as if the pi has not run
Is the file size what you would have expected?
I am now at a loss of what to do next so any help will be appreciated.
kind regards
Paul

**Comment by jdevelop** [comment]
You may want to try one of the Arch Linux images on that SD card: https://archlinuxarm.org/platforms/armv6/raspberry-pi, 

Justto make sure that the SD card is operable.

if that doesn't work either - you may need another SD card, because not all of them are recognized by Pi ( I've got a few cheap ones from e-bay and they aren't recognized by Pi at all, no matter which OS is put on them )

**Comment by appjaws** [comment]
Thanks,
I'll try that later today.
So just to confirm,  the size of the space used on the SD CARD  is correct?

Thanks for your help
Kind regards
Paul Stear



Sent from Samsung Galaxy Note


-------- Original message --------

**Comment by jdevelop** [comment]
Yes, the size is okay. I use buildroot with minimum dependencie and stripped Linux kernel.

**Comment by appjaws** [comment]
I am at a complete loss now.
If I write to a new card using Win32DiskImager the pi zero boots and I have a red light is on on the rfid card and a green light on the raspberrypi zero
http://10.101.1.1 no response.
The screen showed all of the loading process but it now says:-
Welcome to Buildroot
buildroot login:
after some time this is added to the login line [   193.209049] random: crng init done
The screen just sits there now doing nothing.
I don't have any of the leds lit and nothing happens if I insert the rfid dongle.

If I use Cygwin64 Terminal:-
$ dd if=D://Raspberrypi/passkeeper/sdcard.img/sdcard.img of=/dev/sdf bs=1M
132+1 records in
132+1 records out
138412544 bytes (138 MB, 132 MiB) copied, 175.13 s, 790 kB/s
With this card in the zero nothing happens at all, the zero dosen't boot just a quick flash of the green light.

I am sorry to be asking for your help, I would really like to get this working.
again
thanks for your help
kind regards
Paul

**Comment by jdevelop** [comment]
Looks like the SD card is okay and recognized, which is good. Not sure what `Cygwin64` does with DD, but use `Win32DiskImager` onward. 

The yellow ( standby ) led should lit and OLED display should show the progress. If it doesn't - please double-check the wiring.

**Comment by appjaws** [comment]
you were right, I had the ground of the display on pin8 instead of 6.
It has booted and the screen is flashing, saying, Tap the RFID    Key failed,   retry
The yellow LED is lit but very dimly
So again I am asking for help

I'm getting excited now.

**Comment by jdevelop** [comment]
Please check the wiring for the IRQ pin on the RFID reader. The normal operation should look like:

![passkeeper](http://passkeeper-dist.s3.amazonaws.com/passkeeper.jpg)

**Comment by appjaws** [comment]
Well I have checked and double checked the wiring and all is as per your diagram.
I still have the yellow led lit and the screen flashing:-
Key failed, retry
Tap the RFID 
Key failed, retry
I'm wondering if I have a faulty RFID unit, it has a red led on constantly.

Thank you so much for your help so far. From tomorrow I will not be able to work on this until September.
It's so frustrating not to have this working.
Thank again
Paul

**Comment by jdevelop** [comment]
> I still have the yellow led lit and the screen flashing:-

with the screen flashing you have to have the **red** lead lit. The yellow one is for stand-by/self-check indication.

The red led on the RFID is normal, this is just the power.

If you could share a picture with the wiring you have, so I can check it myself (pi and rfid are important, make sure all the contacts/pins are clearly visible ) - that would help a lot, but given that you have the yellow LED on constantly - it seems that something is not right.

**Comment by jdevelop** [comment]
@appjaws I realized that I have the newer version of the PCB wiring than is posted on the website for now, updated the configs and image is available at https://passkeeper-dist.s3.amazonaws.com/sdcard.img.gz

please check it out.

**Comment by appjaws** [comment]
Hi Eugene,
Thanks for the update and new image.
I will try this as soon as I return home.
I did notice that the parts list says 3 560 ohm resistors but only 2 shown on the diagram.
Also the OLED actual pin 1 is gnd and pin 2 is vcc.
Contact you early September after my unit works.
Kind regards
Paul



Sent from Samsung Galaxy Note


-------- Original message --------
